version: "3"

services:

  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "UTC"
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis
    build:
      context: ./docker/redis
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - redis_data:/data

  myadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: mysql

volumes:
  db_data:
  redis_data:

networks:
  frontend:
  backend:
