version: "3"

services:

  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    container_name: redis
    build:
      context: ./docker/redis
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - redis_data:/data
    restart: always

  myadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: mysql # or PMA_ARBITRARY: 1
      # PMA_USER: root
      # PMA_PASSWORD: pass
    restart: always

volumes:
  db_data:
  redis_data:

networks:
  frontend:
  backend:
