## The location of reference is following:
## https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
## if you want to replace the value on starting the process, pass by command line or OS environment.

spring:
  profiles:
    active: local