## The location of reference is here:
## https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
## if you want to replace the value on starting the process, pass by command line or OS environment.

server:
  port: 9000

spring:
  profiles:
    include:
      - logging-production
  datasource:
    url: jdbc:mysql://example.com:3306/test
    username: someone
    password: pass
    platform: mysql
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 1800000
      read-only: false
      auto-commit: false
      connection-init-sql: "SET SESSION sql_mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'"
      connection-test-query: "select 1"
