# Documentation:
# https://circleci.com/docs/2.0/language-java/
version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # check out source code to working directory
      - checkout

      # restore the saved cache after the first run or if `build.gradle` has changed
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies

      # gets the project dependencies
      - run: |
          gradle :simple-todo-common:dependencies
          gradle :simple-todo-api:dependencies

      # saves the project dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: |
          gradle clean
          gradle build
