## The location of reference is following:
## https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
## if you want to replace the value on starting the process, pass by command line or OS environment.

spring:
  profiles:
    active: local
  jackson:
    serialization:
      indent-output: false
      write-dates-as-timestamps: true

logging:
  path: ${APP_LOG_DIR:/var/log/app}

app:
  time-zone: ${APP_TIME_ZONE:Asia/Tokyo}

jwt:
  secret-key: ${JWT_SECRET_KEY:FDqAKV9pO3Fc89GJ66F8yTqWjUSnSTMoV9vgWrOUoo5ijTRJmk1PT2eMCpAg1AwTsjGnCaD4ehmBtKOZ}
